hook.post-receive: using ssh trigger (not rsync)

diff --git a/bin/post-receive b/bin/post-receive
--- a/bin/post-receive
+++ b/bin/post-receive
@@ -15,6 +15,8 @@ export LANG=en_US.UTF-8
 
 _D_VAR="$HOME/var/archlinuxvn/"
 _F_LOCK="$HOME/var/archlinuxvn.lock"
+_F_ARCHIVE="$HOME/static/www/archlinuxvn.org.tgz"
+_S_TUXFAMILY="kyanh@ssh.tuxfamily.org"
 
 msg() {
   echo ":: $*"
@@ -39,11 +41,8 @@ _setup() {
   fi
 
   source $HOME/bin/ssh-agent.sh >/dev/null 2>&1 || die "Can't load ssh configuration"
-  msg "Testing ssh connection"
-  echo ssh -o ConnectTimeout=3 kyanh@ssh.tuxfamily.org uptime >/dev/null
-  if [[ $? -ge 1 ]]; then
-    die "Can't make connect to remote server ssh.tuxfamily.org"
-  fi
+  msg "Testing ssh connection (skipped)"
+  [[ $? -eq 0 ]] || die "Can't make connect to remote server ssh.tuxfamily.org"
   cd $_D_VAR || die "Can't switch to directory $_D_VAR"
 }
 
@@ -109,12 +108,13 @@ _fix_perm() {
   find $_D_VAR/output/ -mindepth 1 -type f -exec chmod 644 {} +
 }
 
+_create_archive() {
+  tar --transform="s,^output,archlinuxvn.org," -cfvz $_F_ARCHIVE output/
+}
+
 _sync() {
   msg "Updating home page archlinuxvn.tuxfamily.org"
-  rsync -rae "ssh -o ConnectTimeout=3" --delete \
-    --exclude="irclogs*" \
-    $_D_VAR/output/ \
-    kyanh@ssh.tuxfamily.org:~/archlinuxvn/archlinuxvn.tuxfamily.org-web/htdocs/
+  ssh -o ConnectTimeout=3 $_S_TUXFAMILY
   if [[ $? -ge 1 ]]; then
     msg "=============================================="
     msg "Error happened when updating pages on tuxfamily."
@@ -168,6 +168,7 @@ _main() {
   _update || die "Something wrong happened during updating process"
   _build
   _fix_perm
+  _create_archive
   _sync
 }
 
