bin/post-receive: generate top-level links for users

diff --git a/bin/post-receive b/bin/post-receive
--- a/bin/post-receive
+++ b/bin/post-receive
@@ -42,9 +42,12 @@ _setup() {
     die "rvm not found. We need ruby1.9"
   fi
 
-  source $HOME/bin/ssh-agent.sh >/dev/null 2>&1 || die "Can't load ssh configuration"
-  msg "Testing ssh connection (skipped)"
-  [[ $? -eq 0 ]] || die "Can't make connect to remote server ssh.tuxfamily.org"
+  # source $HOME/bin/ssh-agent.sh >/dev/null 2>&1 \
+  #   || die "Can't load ssh configuration"
+  #
+  # msg "Testing ssh connection (skipped)"
+  # [[ $? -eq 0 ]] || die "Can't make connect to remote server ssh.tuxfamily.org"
+
   cd $_D_VAR || die "Can't switch to directory $_D_VAR"
 }
 
@@ -78,6 +81,9 @@ _update() {
 
 _update_myself() {
   local _myself="$HOME/hooks/archlinuxvn/post-receive"
+
+  cd $_D_VAR/ && die "Couldn't switch to directory $_D_VAR/"
+
   msg "Updating the build script"
   git archive --format=tar core --remote=~/repositories/archlinuxvn.git \
     | tar --wildcards -xOf - 'bin/post-receive' \
@@ -94,6 +100,8 @@ _update_myself() {
 }
 
 _build() {
+  cd $_D_VAR/ && die "Couldn't switch to directory $_D_VAR/"
+
   msg "Cleaning up the old files"
   nanoc prune --yes
   msg "Rebuilding the static pages"
@@ -119,6 +127,8 @@ _create_www() {
 
 # NOTE: Should be invoked after (create_www)
 _create_archive() {
+  cd $_D_VAR/ && die "Couldn't switch to $_D_VAR/"
+
   msg "Creating local archive for Tuxfamily"
   tar --transform="s,^output,archlinuxvn.org," -czf $_F_ARCHIVE output/
   chmod 644 $_F_ARCHIVE
@@ -174,12 +184,27 @@ _lock_end() {
   rm -f "$_F_LOCK"
 }
 
+_make_links() {
+  local _user
+
+  cd $_D_OUTPUT && die "Oops I couldn't switch to $_D_OUTPUT/"
+
+  find $_D_OUTPUT/blog/ \
+    -mindepth 1 -maxdepth 1 -type d -iname "~*" \
+  | while read _du; do
+      _user="$(basename $_du)"
+      [[ -f "$_D_OUTPUT/$_user" ]] && continue
+      ln -s blog/$_user $_user
+    done
+}
+
 _main() {
   _update_myself
   _setup
   _update || die "Something wrong happened during updating process"
   _build
   _fix_perm
+  _make_links
   _create_www
   _create_archive
   _sync
